# Generated by Django 5.1 on 2024-08-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
