# Generated by Django 5.1 on 2024-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_plat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
