# Generated by Django 5.1 on 2024-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_plat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(default=True, upload_to='plats/'),
            preserve_default=False,
        ),
    ]
