# Generated by Django 5.1 on 2024-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_alter_plat_prix_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email_client',
            field=models.EmailField(default='unknow@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(default='client', max_length=100),
        ),
    ]
