# Generated by Django 5.1 on 2024-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_commande_email_client_commande_nom_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('preparee', 'Préparée'), ('livree', 'Livrée'), ('annulee', 'Annulee')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='disponible',
            field=models.IntegerField(default=5),
        ),
    ]
