# Generated by Django 5.1 on 2024-08-24 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_commande_heure_disponibilite_commande_mode_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='commande',
            name='deposit_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_receipts/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='heure_disponibilite',
            field=models.TimeField(default=datetime.time(10, 46, 54, 611972)),
        ),
    ]
