# Generated by Django 5.1 on 2024-08-25 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_alter_commande_heure_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='heure_disponibilite',
            field=models.TimeField(default=datetime.time(1, 31, 12, 945721)),
        ),
    ]
