# Generated by Django 5.1 on 2024-08-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_remove_commande_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
