# Generated by Django 5.1 on 2024-08-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_alter_plat_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='deposit_receipt',
            field=models.FileField(blank=True, null=True, upload_to='deposit_receipts/'),
        ),
    ]
