# Generated by Django 5.1 on 2024-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0016_alter_commande_deposit_receipt_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='deposit_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_receipts/'),
        ),
    ]
