# Generated by Django 5.1 on 2024-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_alter_commande_deposit_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='deposit_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
