# Generated by Django 5.1 on 2024-08-29 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0018_alter_commande_deposit_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='heure_disponibilite',
            field=models.TimeField(default=datetime.time(21, 47, 31, 5212)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='en_attente', max_length=20),
        ),
    ]
