# Generated by Django 5.1 on 2024-09-01 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0022_alter_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=datetime.time(2, 17, 25, 749115)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='heure_disponibilite',
            field=models.TimeField(default=datetime.time(2, 17, 25, 749115)),
        ),
    ]
